### PR TITLE
Allow Promise for widget factory

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by sccolbert** [comment]
This won't work properly as written. The `event.dropAction` needs to be updated synchronously, otherwise the `Drag.start` method will return the wrong result.

**Comment by sccolbert** [comment]
I think we might need to leave it as-is, and have the generated widget be responsible for asynchronously loading any content.

Can you give an example of a use case which would require resolving a promise?

**Comment by blink1073** [comment]
A FileHandler has an `open(path: string): Promise<Widget>` signature and is resolved when the content is loaded from the server.

**Comment by blink1073** [comment]
Perhaps we override the cursor while it is loading and return the unpopulated widget in the meantime.

**Comment by sccolbert** [comment]
Alternatively, we could assume the meme value to be correct and mark the event as accepted before resolving the promise, but I still don't think that's a good solution.

Consider a file which takes a *really* long term to resolve, or doesn't resolve at all. The dock panel could arbitrarily mutate before the promise resolves, making the computes dock target invalid.

I think the file handler should just return a new widget immediately, and asynchronoulsy load its content.

**Comment by blink1073** [comment]
Yeah, agreed, I'll update the interface.

**Pull request closed without merging**
