### PR TITLE
Dock tab to tab bar by dragging over it instead of the center of its panel.

### PR DESCRIPTION
**Pull request by jjrv**
Not really expecting you to merge without an option to turn this feature on/off. Is there some officially sanctioned way to pass options to widgets / configure PhosphorJS overall functionality?

### CODE REVIEW

**Comment by sccolbert** [comment]
We've actually had some loose discussions about this recently, and thought about moving the center dock area to the tab bar area.

I won't do any updates on this repo since we are merging everything into `phosphor-ui`, but I definitely want to open discussions about this feature over there.

Can you open an issue on that repo about this, and ideally include a gif of the functionality you've implemented?

Thanks!

**Comment by jjrv** [comment]
Done!

**Comment by sccolbert** [comment]
Awesome thanks!

Closing this now that the other issue is open.

**Comment by jasongrout** [comment]
Thanks, and welcome to phosphor!

**Pull request closed without merging**
